ccltkfk базовые стили
JuliaZaykaS/HellEn-school pull request #10
Opened 2021-02-26 19:28 UTC by Grek-88

2021-02-26 19:41 UTC, JuliaZaykaS requested changes

2021-02-26 19:41 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  box-sizing: border-box;
есть в нормалайзе бордер бокс

2021-02-26 19:41 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  font-family: 'Montserrat', sans-serif;
есть переменная на название шрифта

2021-02-26 19:41 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  line-height: 1, 43;
1.43

2021-02-26 19:41 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  font-size: 14px;
шрифт только мобилка. а остальные брейки?

2021-02-26 19:41 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  margin: 0;
глобально уже сбросил, разве тут надо дублировать?

2021-02-26 19:41 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  @media screen and (min-width: var(--tablet)) {
это откуда переменные? в медиа css-переменные не работают

2021-02-26 19:41 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  margin: auto;
вроде же только маржины боковые, а не все?

2021-02-26 19:41 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  display: block;
это лишнее

2021-02-26 20:26 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  box-sizing: border-box;
убрал

2021-02-26 20:28 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  font-family: 'Montserrat', sans-serif;
Где эта переменная?
![image](https://user-images.githubusercontent.com/73738671/109351417-4b5ae480-788a-11eb-96f9-c2e254952bc0.png)

2021-02-26 20:37 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  line-height: 1, 43;
поправил, это притир так запятую форматнул

2021-02-26 20:40 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  font-family: 'Montserrat', sans-serif;
или мне ее создать?

2021-02-26 20:40 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  @media screen and (min-width: var(--tablet)) {
испhавил переменные на $

2021-02-26 20:41 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  display: block;
убрал

2021-02-26 20:46 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  font-size: 14px;
на таблетке такой же, в десктоп добавил

2021-02-26 20:49 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  margin: 0;
действительно же, убрал

2021-02-26 20:50 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  margin: auto;
исправил, хоя спорно, если центрировать элементы в карточке и по вертикали и по горизнтале, но с другой стороны есть падинги на это

2021-02-27 06:22 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  font-family: 'Montserrat', sans-serif;
нужно обновить ветку, Дима вчера делал, я ее смержила вчера

2021-02-27 06:23 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
> +  font-family: 'Montserrat', sans-serif;
![image](https://user-images.githubusercontent.com/72656818/109377605-69056980-78dd-11eb-9cd6-a4fc65349e21.png)

2021-02-27 06:37 UTC, JuliaZaykaS requested changes

2021-02-27 06:37 UTC, JuliaZaykaS commented on src/sass/base/_common.scss
>    padding: 0 20px;
предлагаю декстоп сделать 1280. паддинги можно стандартные по 15рх
я в домашке своей так писала для контейнера, все хорошо тянулось:
@media screen and (min-width: $mobile) {
    max-width: $mobile;
    width: 100%;
  }
  @media screen and (min-width: $tablet) {
    max-width: $tablet;
    width: 100%;
  }
  @media screen and (min-width: $desktop) {
    max-width: $desktop;
    width: 100%;
  }

2021-02-27 09:40 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  font-family: 'Montserrat', sans-serif;
блин изза одной переменненой мне надо создавать новую ветку, зачем вообще перменная со шрифтами, это лишняя строчка, шрифт прописывается один раз в боди, и если захотят поменять его дизайнеры, то мы зайдем в боди и поменяем название, и перменная со шрифтами это лишний код

2021-02-27 09:42 UTC, Grek-88 commented on src/sass/base/_common.scss
> +  font-family: 'Montserrat', sans-serif;
чтобы не создавать новую ветку, давай попробуем смержить с конфликтом эту, и посмотрим что получиться

2021-02-27 10:09 UTC, Grek-88 commented on src/sass/base/_common.scss
>    padding: 0 20px;
сделал 1280 контейнер,
видс 100% не стал писать он и так будет до 1280px  100%

2021-02-27 10:10 UTC, Grek-88 commented
добавил еще .accent

2021-02-27 10:36 UTC, JuliaZaykaS approved these changes

2021-02-27 11:24 UTC, closed without merging