не встает заголовок
JuliaZaykaS/HellEn-school pull request #34
Opened 2021-03-02 07:18 UTC by DariaIkon

не встает заголовок

2021-03-03 12:31 UTC, JuliaZaykaS requested changes

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
> +    }
этот нижний маржин должен начинаться с 0 и идти до таблетки

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>    }
все эти падинги есть в общих стилях контейнера и доп класса section (лежит в паршеле common), поэтому здесь их дублировать не нужно

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>      }
флекс здесь вообще лишний, он ничего не дает
чтобы отменить центрирование заголовка можно использовать text-align: left;

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
на цвет тени есть переменная

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>    }
зачем тень при ховере?

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/partials/how-we-do.html
>                  <div class="how-we-do-icon-list">
абсолютно ненужные дивы для свг, они ничего не дают. все, что у тебя прописано в их стилях идет или в класс иконки или в класс карточки (как паддинги например)

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>  }
лишний класс к диву, паддинги уходят в итем, маржины в стили самой иконки

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>  }
абсолютно ненужные классы, высота у всех одинаковая, ты ее задала, а ширина итак нормально выставляется автоматом

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>    position: relative;
не могу вставить коммент ниже, почему-то, но что-то некоторые свойства шрифтов наследуются от боди
.how-we-do-heading {
  @media screen and (min-width: $desktop) {
    // font-size: 20px;
    line-height: 1.4;
  }
}
.how-we-do-text {
  padding-top: 20px;
  // font-family: Montserrat;

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>    position: relative;
Соня уже написала это в общих стилях, дублировать его тут не нужно. ты у себя оставляешь только то, чего нет в Сонином коде 
&::before {
    content: ' '

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/partials/how-we-do.html
>                  <h3 class="how-we-do-text">
не тот тег

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/partials/how-we-do.html
>                  <div class="before-bottom-line"></div>
пустой див, это моветон. класс добавляется к заголовку

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>    position: relative;
.before-bottom-line { - все паддинги топ заменить на боттом, после того, как перепишешь класс

2021-03-03 12:31 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
> +    }
также в медиа перепиши цифры на переменные например $desktop-1= 1365

2021-03-03 16:18 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
>    }
она есть в макете

2021-03-03 18:20 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
на такую тень нет переменной

2021-03-03 18:22 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
на этот цвет переменной нет переменной

2021-03-03 18:25 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
>    }
они есть у .section а у меня .container

2021-03-03 18:28 UTC, DariaIkon commented on src/partials/how-we-do.html
>                  <div class="before-bottom-line"></div>
сделала

2021-03-03 18:28 UTC, DariaIkon commented on src/partials/how-we-do.html
>                  <h3 class="how-we-do-text">
сделала

2021-03-03 18:29 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
>    position: relative;
сделала

но падинг топ у текста оставила, потому что на псевдолемент падддинг боттом не поставаить

2021-03-03 18:29 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
>  }
сделала

2021-03-03 18:56 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
>  }
сделала

2021-03-03 18:57 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
>      }
сделала

2021-03-03 18:57 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
> +    }
сделала

2021-03-03 18:58 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>    }
зачем дублировать одно и то же? просто добавить класс к секции и все

2021-03-03 18:59 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
![image](https://user-images.githubusercontent.com/72656818/109857467-c6960f00-7c6b-11eb-8942-c9c9c52fdac0.png)

2021-03-03 19:00 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
![image](https://user-images.githubusercontent.com/72656818/109857562-e0375680-7c6b-11eb-9f97-9f79a005c630.png)

2021-03-03 19:01 UTC, JuliaZaykaS commented on src/sass/layouts/_how-we-do.scss
>    }
она одинаковая что в обычном состоянии, что при ховере. зачем писать 2й раз?

2021-03-03 19:28 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
сделала

2021-03-03 19:28 UTC, DariaIkon commented on src/sass/layouts/_how-we-do.scss
>    }
сделала

2021-03-04 08:33 UTC, JuliaZaykaS approved these changes

2021-03-04 08:35 UTC, JuliaZaykaS approved these changes

2021-03-04 08:36 UTC, JuliaZaykaS approved these changes

2021-03-04 17:54 UTC, JuliaZaykaS commented
собрался с ошибками

2021-03-04 17:54 UTC, closed without merging